Repository pulibrary/figgy, pull requests merged in 2018-04, with the labels that each got.

#991 Allows for enlarged/zoomable image viewing in Vue Filemanager
  package-lock.json
  package.json
  valhalla/app/javascript/components/Controls.vue
  valhalla/app/javascript/components/SidePanel.vue
  valhalla/app/javascript/mixins/manifesto-filemanager-mixins.js
  valhalla/app/javascript/test/fixtures/image-collection.js
  valhalla/app/javascript/test/unit/specs/Controls.spec.js
  valhalla/app/javascript/test/unit/specs/__snapshots__/Controls.spec.js.snap
  valhalla/app/javascript/test/unit/specs/manifesto-filemanager-mixins.spec.js
Labels: Review

#993 Remove GeoResources namespace
  .rubocop.yml
  app/controllers/concerns/geoblacklight_document_controller.rb
  app/services/event_generator/geoblacklight_event_generator.rb
  app/services/geo_discovery/abstract_document.rb
  app/services/geo_discovery/document_builder.rb
  app/services/geo_discovery/document_builder/basic_metadata_builder.rb
  app/services/geo_discovery/document_builder/composite_builder.rb
  app/services/geo_discovery/document_builder/date_builder.rb
  app/services/geo_discovery/document_builder/document_helper.rb
  app/services/geo_discovery/document_builder/document_path.rb
  app/services/geo_discovery/document_builder/iiif_builder.rb
  app/services/geo_discovery/document_builder/layer_info_builder.rb
  app/services/geo_discovery/document_builder/references_builder.rb
  app/services/geo_discovery/document_builder/relationship_builder.rb
  app/services/geo_discovery/document_builder/slug_builder.rb
  app/services/geo_discovery/document_builder/spatial_builder.rb
  app/services/geo_discovery/document_builder/wxs.rb
  app/services/geo_discovery/geoblacklight_document.rb
  app/services/geo_metadata_extractor/fgdc.rb
  app/services/geo_metadata_extractor/iso19139.rb
  app/services/geo_resources/discovery/abstract_document.rb
  app/services/geo_resources/discovery/document_builder.rb
  app/services/geo_resources/discovery/document_builder/basic_metadata_builder.rb
  app/services/geo_resources/discovery/document_builder/composite_builder.rb
  app/services/geo_resources/discovery/document_builder/date_builder.rb
  app/services/geo_resources/discovery/document_builder/document_helper.rb
  app/services/geo_resources/discovery/document_builder/document_path.rb
  app/services/geo_resources/discovery/document_builder/iiif_builder.rb
  app/services/geo_resources/discovery/document_builder/layer_info_builder.rb
  app/services/geo_resources/discovery/document_builder/references_builder.rb
  app/services/geo_resources/discovery/document_builder/relationship_builder.rb
  app/services/geo_resources/discovery/document_builder/slug_builder.rb
  app/services/geo_resources/discovery/document_builder/spatial_builder.rb
  app/services/geo_resources/discovery/document_builder/wxs.rb
  app/services/geo_resources/discovery/geoblacklight_document.rb
  app/values/geo_coverage.rb
  app/values/geo_resources/coverage.rb
  spec/controllers/raster_resources_controller_spec.rb
  spec/controllers/vector_resources_controller_spec.rb
  spec/services/event_generator/geoblacklight_event_generator_spec.rb
  spec/services/geo_discovery/abstract_document_spec.rb
  spec/services/geo_discovery/document_builder/wxs_spec.rb
  spec/services/geo_discovery/document_builder_spec.rb
  spec/values/geo_coverage_spec.rb
Labels: Review

#994 Stub rabbit on CleanupDerivativesJob and CreateDerivativesJob
  spec/support/stub_rabbit.rb
Labels: Review

#997 Ensures that only Collection titles are featured within the IIIF Manifest metadata
  app/decorators/valkyrie/resource_decorator.rb
  app/services/pdf_generator/canvas_downloader.rb
  spec/decorators/valkyrie/resource_decorator_spec.rb
Labels: Review, bug

#965 Add jp2 derivatives for jpeg source files
  app/derivative-services/jp2_derivative_service.rb
  app/derivative-services/plum_derivative_service.rb
  spec/derivative_services/jp2_derivative_service_spec.rb
  spec/derivative_services/plum_derivative_service_spec.rb
  spec/fixtures/files/large-jpg-test.jpg
Labels: Review

#1009 Add log warning when scanned resource change_set does not validate on…
  valhalla/app/controllers/concerns/valhalla/resource_controller.rb
Labels: Review

#1013 Add specs for methods without test coverage
  .rubocop.yml
  spec/jobs/create_derivatives_job_spec.rb
  spec/services/event_generator/geoserver_event_generator_spec.rb
  spec/services/geoserver_messaging_client_spec.rb
Labels: Review

#1010 Import shapefiles from old geoportal
  app/change_set_persisters/plum_change_set_persister/apply_remote_metadata.rb
  app/characterization_services/gdal_characterization_service.rb
  app/derivative-services/raster_resource_derivative_service.rb
  app/derivative-services/vector_resource_derivative_service.rb
  app/jobs/ingest_geoportal_record_job.rb
  app/services/geo_discovery/document_builder/layer_info_builder.rb
  spec/fixtures/files/geo_metadata/fgdc.xml
  spec/fixtures/ingest_geoportal/Asia/China/2000_2010CountyCensus.zip
  spec/jobs/ingest_geoportal_record_job_spec.rb
Labels: Review

#1014 Updating `browse-everything` upstream
  Gemfile
  Gemfile.lock
Labels: Review

#1015 Refactor geo thumbnail helper
  app/assets/stylesheets/components/catalog.scss
  app/helpers/thumbnail_helper.rb
  spec/helpers/thumbnail_helper_spec.rb
Labels: Review

#1017 Ensures user ID uniqueness
  app/models/user.rb
  spec/models/user_spec.rb
Labels: enhancement

#1019 Fixes issue with nil geo thumnail id value
  app/helpers/thumbnail_helper.rb
Labels: Review

#1023 Clean geometry values for geoblacklight document
  app/services/geo_discovery/document_builder/layer_info_builder.rb
  spec/services/geo_discovery/document_builder/layer_info_builder_spec.rb
Labels: Review

#1037 Don't require barcode for boxless ephemera folders
  .rubocop.yml
  app/change_sets/boxless_ephemera_folder_change_set.rb
  app/change_sets/ephemera_folder_change_set.rb
  app/change_sets/ephemera_folder_change_set_base.rb
  app/controllers/ephemera_folders_controller.rb
  app/views/records/edit_fields/_barcode.html.erb
  spec/change_sets/boxless_ephemera_folder_change_set_spec.rb
  spec/features/ephemera_folder_spec.rb
Labels: Review

#1036 Update Cicognara export
  app/services/cicognara_csv.rb
  spec/services/cicognara_csv_spec.rb
Labels: Review

#1039 Add a simple draft-publish workflow for use with plates (SimpleResource), refs #1031
  app/models/controlled_vocabulary.rb
  app/models/draft_publish_workflow.rb
  app/models/search_builder.rb
  config/locales/en.yml
  spec/models/draft_publish_workflow_spec.rb
Labels: Review

#1047 Modify permissions to allow for anonymous downloading of geo files
  app/models/ability.rb
  spec/models/ability_spec.rb
  valhalla/app/controllers/valhalla/downloads_controller.rb
Labels: Review

#1046 Add SimpleResource to the home page (no icon yet)
  .rubocop.yml
  app/change_sets/simple_resource_change_set.rb
  app/helpers/application_helper.rb
  app/models/controlled_vocabulary.rb
  app/views/catalog/_home_text.html.erb
  spec/change_sets/simple_resource_change_set_spec.rb
  spec/features/root_spec.rb
Labels: Review

#1052 Fixes Vue Filemanager bug when dealing with blank labels
  valhalla/app/javascript/mixins/manifesto-filemanager-mixins.js
  valhalla/app/javascript/test/fixtures/manifest.js
  valhalla/app/javascript/test/unit/specs/manifesto-filemanager-mixins.spec.js
Labels: Review

#1054 Add test for ephemera folder indexer
  spec/indexers/ephemera_folder_indexer_spec.rb
Labels: Review

#1055 Add new class for workflow registry (not yet in use)
  app/models/workflow_registry.rb
  config/initializers/workflows.rb
  spec/models/workflow_registry_spec.rb
Labels: Review

#1058 Adding objects imported from METS to collections referenced in IsPartOf relation
  app/jobs/ingest_mets_job.rb
  app/models/mets_document.rb
  app/models/mets_document/factory.rb
  spec/jobs/ingest_mets_job_spec.rb
  spec/models/mets_document_spec.rb
Labels: Review

#1059 Fixes `SimpleResource` membership admin. controls and PUL logo links in Manifests
  app/decorators/simple_resource_decorator.rb
  app/services/manifest_builder/logo_builder.rb
  app/views/catalog/_members_simple_resource.html.erb
  config/routes.rb
Labels: Review

#1021 Using an upstream bug resolution in order to ensure that file system paths for `browse-everything` with punctuation can be resolved
  Gemfile
  Gemfile.lock
Labels: Review, bug

#1063 Don't generate thumbnail without derivative.
  app/services/manifest_builder/thumbnail_builder.rb
  spec/services/manifest_builder_spec.rb
Labels: Review

#1064 Nightly builds.
  .circleci/config.yml
Labels: Review

#1066 Ensures that the FileManager interface is offered for `SimpleResources`
  app/helpers/application_helper.rb
  config/routes.rb
  spec/routing/simple_resource_routes_spec.rb
Labels: Review

#1068 Add specs documenting per-user display of ephemera boxes
  spec/controllers/catalog_controller_spec.rb
Labels: Review

#1065 Push state-based visibility logic into workflow classes and decorators
  app/change_sets/ephemera_box_change_set.rb
  app/change_sets/ephemera_folder_change_set_base.rb
  app/change_sets/media_resource_change_set.rb
  app/change_sets/raster_resource_change_set.rb
  app/change_sets/scanned_map_change_set.rb
  app/change_sets/scanned_resource_change_set.rb
  app/change_sets/simple_resource_change_set.rb
  app/change_sets/vector_resource_change_set.rb
  app/decorators/ephemera_box_decorator.rb
  app/decorators/ephemera_folder_decorator.rb
  app/decorators/valkyrie/resource_decorator.rb
  app/indexers/ephemera_folder_indexer.rb
  app/models/ability.rb
  app/models/book_workflow.rb
  app/models/box_workflow.rb
  app/models/draft_publish_workflow.rb
  app/models/folder_workflow.rb
  app/models/search_builder.rb
  app/models/workflow_registry.rb
  config/initializers/workflows.rb
  spec/decorators/ephemera_box_decorator_spec.rb
  spec/decorators/ephemera_folder_decorator_spec.rb
  spec/decorators/valkyrie/resource_decorator_spec.rb
  spec/factories/simple_resource.rb
  spec/models/book_workflow_spec.rb
  spec/models/box_workflow_spec.rb
  spec/models/draft_publish_workflow_spec.rb
  spec/models/folder_workflow_spec.rb
  spec/models/workflow_registry_spec.rb
Labels: Review

#1077 Downgrade chromedriver to prevent incompatibility with latest available Chrome
  .circleci/config.yml
Labels: Review

#1078 Increase test coverage for ingest geoportal record job
  app/jobs/ingest_geoportal_record_job.rb
  spec/jobs/ingest_geoportal_record_job_spec.rb
Labels: Review

#1074 Change `indexable?` to `index_read_groups?` to be more accurate
  app/decorators/ephemera_folder_decorator.rb
  app/indexers/ephemera_folder_indexer.rb
  app/models/folder_workflow.rb
  spec/decorators/ephemera_folder_decorator_spec.rb
  spec/decorators/valkyrie/resource_decorator_spec.rb
Labels: Review

#1072 Add SimpleResource to discoverable classes in search_builder
  app/models/search_builder.rb
  spec/controllers/catalog_controller_spec.rb
Labels: Review

#1073 Add rake task to bulk-update state
  app/services/update_state.rb
  lib/tasks/bulk.rake
  spec/services/update_state_spec.rb
Labels: Review

#1070 Ensures that links for editing and deleting resources are only rendered for users with the appropriate permissions
  app/views/catalog/_admin_controls_default.html.erb
  app/views/catalog/_admin_controls_ephemera_box.html.erb
  app/views/catalog/_admin_controls_ephemera_folder.html.erb
  app/views/catalog/_admin_controls_ephemera_term.html.erb
  app/views/catalog/_admin_controls_file_set.html.erb
  spec/views/catalog/_admin_controls_default.html.erb_spec.rb
  spec/views/catalog/_admin_controls_ephemera_box.html.erb_spec.rb
  spec/views/catalog/_admin_controls_ephemera_folder.html.erb_spec.rb
  spec/views/catalog/_admin_controls_ephemera_term.html.erb_spec.rb
  spec/views/catalog/_admin_controls_file_set.html.erb_spec.rb
Labels: Review

#1086 Add ArchivalMediaCollection, resolves #1076
  app/models/archival_media_collection.rb
  spec/factories/archival_media_collection.rb
  spec/models/archival_media_collection_spec.rb
Labels: Review

#1080 Add OCR to Scanned/SimpleResources
  .circleci/config.yml
  .rubocop.yml
  app/change_set_persisters/plum_change_set_persister.rb
  app/change_set_persisters/plum_change_set_persister/update_ocr.rb
  app/change_sets/file_set_change_set.rb
  app/change_sets/scanned_resource_change_set.rb
  app/change_sets/simple_resource_change_set.rb
  app/controllers/file_sets_controller.rb
  app/decorators/scanned_resource_decorator.rb
  app/derivative-services/hocr_derivative_service.rb
  app/derivative-services/plum_derivative_service.rb
  app/jobs/run_ocr_job.rb
  app/models/ability.rb
  app/models/controlled_vocabulary.rb
  app/models/file_set.rb
  app/services/manifest_builder.rb
  app/services/manifest_builder/canvas_builder.rb
  app/services/manifest_builder/canvas_rendering_builder.rb
  app/services/tesseract.rb
  app/views/records/edit_fields/_ocr_language.html.erb
  config/locales/en.yml
  config/locales/simple_form.en.yml
  config/routes.rb
  spec/change_set_persisters/plum_change_set_persister_spec.rb
  spec/controllers/catalog_controller_spec.rb
  spec/controllers/file_sets_controller_spec.rb
  spec/derivative_services/hocr_derivative_service_spec.rb
  spec/fixtures/files/abstract.tiff
  spec/models/ability_spec.rb
  spec/models/controlled_vocabulary_spec.rb
  spec/services/manifest_builder_spec.rb
  spec/services/tesseract_spec.rb
  spec/shared_specs/controllers/base_resource_controller.rb
Labels: Review

#1089 Add controller, link to create Archival Media Collection
  app/change_sets/archival_media_collection_change_set.rb
  app/controllers/archival_media_collections_controller.rb
  app/views/catalog/_home_text.html.erb
  app/views/shared/_add_content.html.erb
  config/routes.rb
  spec/controllers/archival_media_collections_controller_spec.rb
  spec/features/root_spec.rb
Labels: Review

#1099 Move position of coverage on Vector and Raster edit pages
  app/change_sets/raster_resource_change_set.rb
  app/change_sets/vector_resource_change_set.rb
Labels: Review

#1093 Removes coverage from scanned map edit page
  app/change_sets/scanned_map_change_set.rb
  spec/change_set_persisters/plum_change_set_persister_spec.rb
  spec/features/scanned_map_spec.rb
  spec/fixtures/files/bibdata/10001789.jsonld
Labels: Review

#1067 Implements the `MintIdentifier` hook for the `PlumChangeSetPersister`
  .rubocop.yml
  app/change_set_persisters/plum_change_set_persister.rb
  app/change_set_persisters/plum_change_set_persister/apply_remote_metadata.rb
  app/change_set_persisters/plum_change_set_persister/mint_identifier.rb
  app/change_sets/simple_resource_change_set.rb
  app/decorators/simple_resource_decorator.rb
  app/decorators/valkyrie/resource_decorator.rb
  app/models/book_workflow.rb
  app/models/box_workflow.rb
  app/models/draft_publish_workflow.rb
  app/models/folder_workflow.rb
  spec/change_set_persisters/plum_change_set_persister/mint_identifier_spec.rb
  spec/change_set_persisters/plum_change_set_persister_spec.rb
  spec/controllers/catalog_controller_spec.rb
  spec/controllers/reports_controller_spec.rb
  spec/controllers/scanned_maps_controller_spec.rb
  spec/controllers/scanned_resources_controller_spec.rb
  spec/controllers/simple_resources_controller_spec.rb
  spec/decorators/valkyrie/resource_decorator_spec.rb
  spec/factories/raster_resource.rb
  spec/factories/scanned_map.rb
  spec/factories/scanned_resource.rb
  spec/factories/simple_resource.rb
  spec/factories/vector_resource.rb
  spec/features/simple_resource_spec.rb
  spec/models/ability_spec.rb
  spec/models/book_workflow_spec.rb
  spec/models/box_workflow_spec.rb
  spec/models/draft_publish_workflow_spec.rb
  spec/models/file_set_spec.rb
  spec/models/folder_workflow_spec.rb
  spec/queries/find_identifiers_to_reconcile_spec.rb
  spec/requests/scanned_resource_spec.rb
  spec/services/cicognara_csv_spec.rb
  spec/services/event_generator/geoblacklight_event_generator_spec.rb
  spec/shared_specs/controllers/base_resource_controller.rb
  spec/utils/data_seeder_spec.rb
Labels: in progress

#1103 Fix collection manifests with MVWs.
  app/services/manifest_builder/thumbnail_builder.rb
  spec/services/manifest_builder_spec.rb
Labels: Review

#1114 Filter raster children from scanned map manifests
  app/services/manifest_builder.rb
  spec/services/manifest_builder_spec.rb
Labels: Review

#1112 Seed additional geo resources
  app/utils/data_seeder.rb
  spec/utils/data_seeder_spec.rb
Labels: Review

#1117 Document tesseract dependency, fixes #1109
  README.md
Labels: Review

#1111 OpenSeadragon no longer breaks after Apply Changes
  valhalla/app/javascript/components/Controls.vue
  valhalla/app/javascript/components/FilesetForm.vue
  valhalla/app/javascript/test/unit/specs/__snapshots__/Controls.spec.js.snap
Labels: Review

#1113 Maintain newlines when saving text version of HOCR
  app/derivative-services/hocr_derivative_service.rb
  spec/derivative_services/hocr_derivative_service_spec.rb
  spec/fixtures/hocr.hocr
  spec/fixtures/ocr.txt
Labels: Review

#1124 Add portion note to geo resources
  app/change_sets/raster_resource_change_set.rb
  app/change_sets/scanned_map_change_set.rb
  app/change_sets/vector_resource_change_set.rb
  app/decorators/raster_resource_decorator.rb
  app/decorators/scanned_map_decorator.rb
  app/decorators/vector_resource_decorator.rb
  spec/decorators/raster_resource_decorator_spec.rb
  spec/decorators/scanned_map_decorator_spec.rb
  spec/decorators/vector_resource_decorator_spec.rb
  spec/features/scanned_map_spec.rb
Labels: Review

#1130 Don't merge imported identifier in geoblacklight metadata decorator
  app/decorators/geoblacklight_metadata_decorator.rb
  spec/services/geo_discovery/document_builder_spec.rb
Labels: Review
