Repository pulibrary/figgy, pull requests merged in 2018-09, with the labels that each got.

#1788 Multi-volume map sets
  app/services/manifest_builder.rb
  app/utils/data_seeder.rb
  spec/services/manifest_builder_spec.rb
  spec/utils/data_seeder_spec.rb
Labels: Review

#1787 Disable edit for SimpleResource.
  app/controllers/scanned_resources_controller.rb
  spec/features/simple_resource_spec.rb
Labels: Review

#1789 Extract MODS metadata for PUDL0036
  .rubocop.yml
  app/models/ark_with_title.rb
  app/models/mets_document.rb
  app/models/mets_document/mods_document.rb
  spec/fixtures/mets/pudl0036-135-01.mets
  spec/models/mets_document/mods_document_spec.rb
Labels: Review

#1790 Fix UUID identifiers in Ivy Lee.
  app/models/mets_document.rb
  app/models/mets_document/mods_document.rb
  spec/models/mets_document/mods_document_spec.rb
  spec/models/mets_document_spec.rb
Labels: Review

#1792 Add missing metadata for WA-WC064
  app/models/mets_document.rb
  app/models/mets_document/mods_document.rb
  spec/fixtures/mets/pudl0017-wc064.mets
  spec/models/mets_document/mods_document_spec.rb
Labels: Review

#1793 Add photographer to SimpleResourceChangeSet
  app/change_sets/simple_resource_change_set.rb
Labels: Review

#1798 Updating rubyzip to release 1.2.2
  Gemfile
  Gemfile.lock
Labels: Review

#1804 Fix PUDL0017 when there's no extra series info
  app/models/mets_document/mods_document.rb
  spec/fixtures/mets/pudl0017-wc064-s-s2687.mets
  spec/models/mets_document_spec.rb
Labels: Review

#1796 Changes for PUDL0100
  app/change_sets/simple_resource_change_set.rb
  app/decorators/ephemera_vocabulary_decorator.rb
  app/decorators/scanned_resource_decorator.rb
  app/models/mets_document.rb
  app/models/mets_document/mods_document.rb
  app/models/solr_document.rb
  spec/decorators/scanned_resource_decorator_spec.rb
  spec/fixtures/mets/pudl0100-lc-egx_0003.mets
  spec/helpers/blacklight_helper_spec.rb
  spec/jobs/ingest_mets_job_spec.rb
  spec/models/mets_document/mods_document_spec.rb
Labels: Review

#1808 Add CoveragePoint resource in app/values
  app/change_sets/simple_resource_change_set.rb
  app/characterization_services/mediainfo_characterization_service.rb
  app/models/schema/common.rb
  app/values/coverage_point.rb
  spec/values/coverage_point_spec.rb
Labels: Review

#1806 Small cleanups to change_set_persister_spec
  spec/change_set_persisters/change_set_persister_spec.rb
Labels: Review

#1503 Migrate pul_metadata_services; Use the `<unittitle>` to extract titles for `MediaResources`
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/change_set_persisters/change_set_persister/apply_remote_metadata.rb
  app/jobs/ingest_archival_media_bag_job.rb
  app/models/archival_media_bag_parser.rb
  app/models/remote_record.rb
  app/services/pul_metadata_services.rb
  app/services/pul_metadata_services/bib_record.rb
  app/services/pul_metadata_services/client.rb
  app/services/pul_metadata_services/pulfa_record.rb
  spec/change_set_persisters/change_set_persister_spec.rb
  spec/fixtures/files/bibdata/10068705.mrx
  spec/fixtures/files/bibdata/1160682.jsonld
  spec/fixtures/files/bibdata/1160682.mrx
  spec/fixtures/files/bibdata/1160682b.mrx
  spec/fixtures/files/bibdata/345682.jsonld
  spec/fixtures/files/bibdata/345682.mrx
  spec/fixtures/files/bibdata/345682b.mrx
  spec/fixtures/files/bibdata/345682c.mrx
  spec/fixtures/files/bibdata/4609321.jsonld
  spec/fixtures/files/bibdata/4609321.mrx
  spec/fixtures/files/bibdata/4609321b.mrx
  spec/fixtures/files/bibdata/4609321c.mrx
  spec/fixtures/files/bibdata/7214786.jsonld
  spec/fixtures/files/bibdata/7214786.mrx
  spec/fixtures/files/bibdata/7214786b.mrx
  spec/fixtures/files/pulfa/AC057_c18.xml
  spec/fixtures/files/pulfa/AC123_c00004.xml
  spec/fixtures/files/pulfa/C06520.xml
  spec/fixtures/files/pulfa/C0967_c0001.xml
  spec/fixtures/files/pulfa/RBD1/c13076.xml
  spec/fixtures/files/pulfa/RBD1/c13076_full.xml
  spec/jobs/ingest_archival_media_bag_job_spec.rb
  spec/models/remote_record/pulfa_record_spec.rb
  spec/services/pul_metadata_services/bib_record_spec.rb
  spec/services/pul_metadata_services/client_spec.rb
  spec/services/pul_metadata_services/pulfa_record/attributes_spec.rb
  spec/services/pul_metadata_services/pulfa_record/collection_attributes_spec.rb
  spec/services/pul_metadata_services/pulfa_record/media_resource_attributes_spec.rb
  spec/services/pul_metadata_services/pulfa_record_spec.rb
  spec/support/stub_bibdata.rb
Labels: Review

#1730 Implements the IngestIntermediateFileJob and BulkIngestIntermediateService for appending intermediate files
  .rubocop.yml
  app/derivative-services/image_derivative_service.rb
  app/derivative-services/jp2_derivative_service.rb
  app/jobs/ingest_intermediate_file_job.rb
  app/models/file_set.rb
  app/services/bulk_ingest_intermediate_service.rb
  app/services/file_appender/file_resources.rb
  lib/tasks/bulk.rake
  spec/derivative_services/image_derivative_service_spec.rb
  spec/derivative_services/jp2_derivative_service_spec.rb
  spec/fixtures/files/pudl0044/originals_no_watermark/123456/00000001.tif
  spec/jobs/ingest_intermediate_file_job_spec.rb
  spec/services/bulk_ingest_intermediate_service_spec.rb
Labels: Review

#1810 Mods subtitle, coverage_point to allow ingest of pudl0017
  app/models/mets_document.rb
  app/models/mets_document/mods_document.rb
  spec/fixtures/mets/pudl0038-mp090-0894.mets
  spec/models/mets_document/mods_document_spec.rb
  spec/models/mets_document_spec.rb
Labels: Review

#1815 Allow for blank holding location
  app/models/mets_document.rb
  spec/fixtures/mets/pudl0100-lc-egx_0003-nolocation.mets
  spec/models/mets_document_spec.rb
Labels: Review

#1819 Add GraphQL query for searching by BibID
  app/graphql/types/query_type.rb
  app/graphql/types/resource.rb
  app/graphql/types/scanned_map_type.rb
  app/graphql/types/scanned_resource_type.rb
  spec/graphql/types/query_type_spec.rb
  spec/graphql/types/scanned_map_type_spec.rb
  spec/graphql/types/scanned_resource_type_spec.rb
Labels: Review

#1818 Open up GraphQL to public
  app/models/ability.rb
  spec/controllers/graphql_controller_spec.rb
  spec/models/ability_spec.rb
Labels: Review

#1813 Adds title with nonsort tag, publisher and published_date
  .rubocop.yml
  app/change_sets/simple_resource_change_set.rb
  app/models/mets_document.rb
  app/models/mets_document/mods_document.rb
  app/models/schema/common.rb
  spec/fixtures/mets/pudl0009-1-0001.mets
  spec/fixtures/mets/pudl0009-1-0144.mets
  spec/fixtures/pudl0009-1-0001.mets
  spec/models/mets_document/mods_document_spec.rb
Labels: Review

#1824 Validate that PDFs exist in decorator
  app/decorators/scanned_resource_decorator.rb
  spec/decorators/scanned_resource_decorator_spec.rb
Labels: Review

#1826 Display JSON-LD for simple resources.
  .rubocop.yml
  app/models/concerns/linked_data/linked_resource_factory.rb
  app/models/concerns/linked_data/linked_simple_resource.rb
  spec/controllers/catalog_controller_spec.rb
Labels: Review

#1827 Fix show page rendered coverage
  app/decorators/raster_resource_decorator.rb
  app/decorators/scanned_map_decorator.rb
  app/decorators/vector_resource_decorator.rb
  spec/decorators/raster_resource_decorator_spec.rb
  spec/decorators/scanned_map_decorator_spec.rb
  spec/decorators/vector_resource_decorator_spec.rb
Labels: Review

#1828 Support ArkWithTitle in PartOf
  app/models/concerns/linked_data/linked_simple_resource.rb
  spec/controllers/catalog_controller_spec.rb
Labels: Review

#1830 Don't display thumbnail ID in JSON-LD.
  app/models/concerns/linked_data/linked_simple_resource.rb
Labels: Review

#1833 Don't load all members for human_readable_type
  app/decorators/scanned_resource_decorator.rb
  app/wayfinders/scanned_resource_wayfinder.rb
  spec/wayfinders/wayfinder_spec.rb
Labels: Review

#1835 Introduces rack-cors in order to permit cross domain queries for GraphQL
  Gemfile
  Gemfile.lock
  config/application.rb
Labels: Review

#1847 Adding support for auth tokens to downloads controller
  app/controllers/downloads_controller.rb
  spec/controllers/downloads_controller_spec.rb
Labels: Review

#1846 Split mailer test into smaller fixtures to reduce vulnerability to order
  spec/mailers/collections_mailer_spec.rb
Labels: Review

#1848 Adds browserstack requirements and LUX upgrades
  README.md
  browserstack-logo.svg
  package.json
Labels: Review

#1853 Don't reindex ProcessedEvent
  app/queries/memory_efficient_all_query.rb
  app/services/reindexer.rb
  spec/queries/memory_efficient_all_query_spec.rb
  spec/services/reindexer_spec.rb
Labels: Review

#1858 Add Template to search builder blacklist
  app/models/search_builder.rb
  spec/controllers/catalog_controller_spec.rb
Labels: Review

#1845 Add figgy_title values to index
  app/indexers/title_indexer.rb
  app/models/grouping.rb
  config/initializers/valkyrie.rb
  spec/indexers/title_indexer_spec.rb
  spec/models/grouping_spec.rb
Labels: Review

#1862 Remove unused pudl0009-1-0001.mets file
  spec/fixtures/pudl0009-1-0001.mets
Labels: Review, cleanup

#1865 Only include complete objects with BibIDs in the identifiers-to-reconcile report
  app/controllers/reports_controller.rb
  app/queries/find_identifiers_to_reconcile.rb
  spec/controllers/reports_controller_spec.rb
  spec/queries/find_identifiers_to_reconcile_spec.rb
Labels: Review

#1879 Allow transition straight to complete in book workflow
  app/models/book_workflow.rb
  spec/change_sets/scanned_resource_change_set_spec.rb
  spec/models/book_workflow_spec.rb
  spec/validators/state_validator_spec.rb
Labels: Review

#1867 Add rights statement validator and use in all relevant change sets
  app/change_sets/boxless_ephemera_folder_change_set.rb
  app/change_sets/ephemera_box_change_set.rb
  app/change_sets/ephemera_folder_change_set.rb
  app/change_sets/ephemera_folder_change_set_base.rb
  app/change_sets/media_resource_change_set.rb
  app/change_sets/raster_resource_change_set.rb
  app/change_sets/scanned_resource_change_set.rb
  app/change_sets/simple_resource_change_set.rb
  app/change_sets/vector_resource_change_set.rb
  app/validators/rights_statement_validator.rb
  spec/change_sets/boxless_ephemera_folder_change_set_spec.rb
  spec/change_sets/ephemera_box_change_set_spec.rb
  spec/change_sets/ephemera_folder_change_set_spec.rb
  spec/change_sets/media_resource_change_set_spec.rb
  spec/change_sets/raster_resource_change_set_spec.rb
  spec/change_sets/scanned_resource_change_set_spec.rb
  spec/change_sets/simple_resource_change_set_spec.rb
  spec/change_sets/vector_resource_change_set_spec.rb
  spec/controllers/ephemera_boxes_controller_spec.rb
  spec/controllers/ephemera_folders_controller_spec.rb
  spec/controllers/raster_resources_controller_spec.rb
  spec/controllers/scanned_maps_controller_spec.rb
  spec/controllers/scanned_resources_controller_spec.rb
  spec/controllers/vector_resources_controller_spec.rb
  spec/shared_specs/change_sets/change_set.rb
  spec/shared_specs/controllers/base_resource_controller.rb
  spec/validators/rights_statement_validator_spec.rb
Labels: Review

#1882 Allow for orphaned file sets in fixity dashboard
  app/views/fixity_dashboard/_fixity_table.html.erb
  spec/views/fixity_dashboard/_fixity_table.html.erb_spec.rb
Labels: Review

#1873 Change catalog controller to use new figgy_title fields
  app/controllers/catalog_controller.rb
Labels: Review

#1885 Remove spaces in #created date range for consistency with vals in #date_created
  app/decorators/archival_media_collection_decorator.rb
  app/decorators/scanned_resource_decorator.rb
  spec/decorators/archival_media_collection_decorator_spec.rb
  spec/decorators/scanned_resource_decorator_spec.rb
Labels: Review

#1863 Rename bulk:update_state task to update_attrs and add rights_statement option
  app/services/bulk_edit_service.rb
  app/services/update_state.rb
  lib/tasks/bulk.rake
  spec/services/bulk_edit_service_spec.rb
  spec/services/update_state_spec.rb
Labels: Review

#1889 Add upload_set_id to MediaResource, use it during archival media ingest
  .rubocop.yml
  app/change_sets/media_resource_change_set.rb
  app/decorators/media_resource_decorator.rb
  app/jobs/ingest_archival_media_bag_job.rb
  app/models/media_resource.rb
  spec/jobs/ingest_archival_media_bag_job_spec.rb
  spec/models/media_resource_spec.rb
Labels: Review

#1890 Reindex resources when collection/project they belong to changes title
  app/change_set_persisters/change_set_persister.rb
  app/change_set_persisters/change_set_persister/reindex_collection_members.rb
  app/indexers/collection_indexer.rb
  spec/change_set_persisters/change_set_persister_spec.rb
Labels: Review

#1892 Index a resource's collection titles as text for better searching
  app/indexers/collection_indexer.rb
  spec/indexers/collection_indexer_spec.rb
Labels: Review

#1894 Update geo_works-derivatives gem
  Gemfile
  Gemfile.lock
Labels: Review

#1896 Don't re-query for filesets in ManifestBuilder
  app/services/manifest_builder.rb
  app/services/manifest_builder/thumbnail_builder.rb
  spec/services/manifest_builder_spec.rb
Labels: Review

#1900 Update link text for members of a collection
  app/views/catalog/_members_archival_media_collection.html.erb
  app/views/catalog/_members_collection.html.erb
  spec/features/archival_media_collection_spec.rb
  spec/features/collections_spec.rb
Labels: Review

#1908 Updates Faraday and uses the browse-everything branch for Google Drive paging
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.scss
  spec/change_set_persisters/change_set_persister_spec.rb
  spec/controllers/scanned_resources_controller_spec.rb
Labels: Review

#1880 Find folders with genres pre-loaded
  Gemfile
  Gemfile.lock
  app/controllers/ephemera_boxes_controller.rb
  app/controllers/ephemera_projects_controller.rb
  app/decorators/ephemera_box_decorator.rb
  app/decorators/ephemera_folder_decorator.rb
  app/decorators/ephemera_project_decorator.rb
  app/models/folder_data_source.rb
  app/models/resource.rb
  app/queries/find_members_with_relationship.rb
  app/wayfinders/ephemera_box_wayfinder.rb
  app/wayfinders/ephemera_project_wayfinder.rb
  config/environments/development.rb
  config/initializers/valkyrie.rb
  spec/controllers/ephemera_projects_controller_spec.rb
  spec/queries/find_members_with_relationship_spec.rb
Labels: Review

#1914 Update file checksum in FgdcUpdateService
  app/jobs/update_fgdc_onlink_job.rb
  app/services/fgdc_update_service.rb
  spec/jobs/update_fgdc_onlink_job_spec.rb
Labels: Review

#1915 Ensures that IngestArchivalMediaBagJob can ingest bags without images as valid MediaResources
  Gemfile
  Gemfile.lock
  app/jobs/ingest_archival_media_bag_job.rb
  spec/fixtures/av/la_c0652_2017_05_bag3/bag-info.txt
  spec/fixtures/av/la_c0652_2017_05_bag3/bagit.txt
  spec/fixtures/av/la_c0652_2017_05_bag3/data/32101047382492.xml
  spec/fixtures/av/la_c0652_2017_05_bag3/data/32101047382492_1_a.mp3
  spec/fixtures/av/la_c0652_2017_05_bag3/data/32101047382492_1_i.wav
  spec/fixtures/av/la_c0652_2017_05_bag3/data/32101047382492_1_pm.wav
  spec/fixtures/av/la_c0652_2017_05_bag3/manifest-sha256.txt
  spec/fixtures/av/la_c0652_2017_05_bag3/tagmanifest-md5.txt
  spec/fixtures/av/la_c0652_2017_05_bag3/tagmanifest-sha1.txt
  spec/jobs/ingest_archival_media_bag_job_spec.rb
Labels: Review

#1913 Ensuring that derivative FileMetadata is deleted from FileSets when IngestIntermediateFileJob appends an intermediate file for a resource
  app/jobs/ingest_intermediate_file_job.rb
  spec/change_sets/file_set_change_set_spec.rb
  spec/jobs/ingest_intermediate_file_job_spec.rb
Labels: Review

#1912 Use Valkyrie-Sequel
  Gemfile
  Gemfile.lock
  app/adapters/indexing_adapter.rb
  app/queries/count_members.rb
  app/queries/file_sets_sorted_by_updated.rb
  app/queries/find_by_string_property.rb
  app/queries/find_ephemera_term_by_label.rb
  app/queries/find_ephemera_vocabulary_by_label.rb
  app/queries/find_fixity_failures.rb
  app/queries/find_identifiers_to_reconcile.rb
  app/queries/find_saved_ids.rb
  app/queries/memory_efficient_all_query.rb
  config/initializers/valkyrie.rb
  spec/services/valkyrie1_migrator_spec.rb
  spec/support/database_cleaner.rb
Labels: Review

#1923 Fix query to work with Sequel.
  app/queries/find_members_with_relationship.rb
Labels: Review

#1924 Enable Sequel datadog tracing.
  Gemfile.lock
  config/initializers/datadog.rb
Labels: Review

#1925 Introduces a work-around for Faraday HTTP proxy warnings using ENV['NO_PROXY']
  spec/spec_helper.rb
Labels: enhancement

#1920 Modifies the handling of files within archival media bags in order to ensure that files for sides with multiple parts are ingested as separate FileSets
  .rubocop.yml
  app/jobs/ingest_archival_media_bag_job.rb
  app/models/archival_media_bag_parser.rb
  app/models/file_set.rb
  app/models/ingestable_audio_file.rb
  app/validators/unique_archival_media_barcode_validator.rb
  spec/change_sets/archival_media_collection_change_set_spec.rb
  spec/fixtures/av/a_c0652_2017_05_bag3/bag-info.txt
  spec/fixtures/av/a_c0652_2017_05_bag3/bagit.txt
  spec/fixtures/av/a_c0652_2017_05_bag3/data/32101047382492.xml
  spec/fixtures/av/a_c0652_2017_05_bag3/data/32101047382492_1_a.mp3
  spec/fixtures/av/a_c0652_2017_05_bag3/data/32101047382492_1_i.wav
  spec/fixtures/av/a_c0652_2017_05_bag3/data/32101047382492_1_pm.wav
  spec/fixtures/av/a_c0652_2017_05_bag3/manifest-sha256.txt
  spec/fixtures/av/a_c0652_2017_05_bag3/tagmanifest-md5.txt
  spec/fixtures/av/a_c0652_2017_05_bag3/tagmanifest-sha1.txt
  spec/fixtures/av/la_c0652_2017_05_bag4/bag-info.txt
  spec/fixtures/av/la_c0652_2017_05_bag4/bagit.txt
  spec/fixtures/av/la_c0652_2017_05_bag4/data/32101047382492.xml
  spec/fixtures/av/la_c0652_2017_05_bag4/data/32101047382492_1_p1_a.mp3
  spec/fixtures/av/la_c0652_2017_05_bag4/data/32101047382492_1_p1_i.wav
  spec/fixtures/av/la_c0652_2017_05_bag4/data/32101047382492_1_p1_pm.wav
  spec/fixtures/av/la_c0652_2017_05_bag4/data/32101047382492_1_p2_a.mp3
  spec/fixtures/av/la_c0652_2017_05_bag4/data/32101047382492_1_p2_i.wav
  spec/fixtures/av/la_c0652_2017_05_bag4/data/32101047382492_1_p2_pm.wav
  spec/fixtures/av/la_c0652_2017_05_bag4/manifest-sha256.txt
  spec/fixtures/av/la_c0652_2017_05_bag4/tagmanifest-md5.txt
  spec/fixtures/av/la_c0652_2017_05_bag4/tagmanifest-sha1.txt
  spec/jobs/ingest_archival_media_bag_job_spec.rb
  spec/models/ingestable_audio_file_spec.rb
Labels: Review

#1929 Validate idle sequel connections
  Gemfile.lock
Labels: Review

#1922 Raises an instance of ArgumentError within BulkIngestService#attach_each_dir and BulkIngestService#attach_dir when directory paths point towards non-existent or empty directories
  .rubocop.yml
  app/services/bulk_ingest_service.rb
  spec/services/bulk_ingest_service_spec.rb
Labels: Review

#1931 Remove unnecessary om code
  app/javascript/components/Controls.vue
  app/javascript/components/FilesetForm.vue
  app/javascript/components/FilesetsForm.vue
  app/javascript/components/ResourceForm.vue
  app/javascript/components/SidePanel.vue
  app/javascript/components/Thumbnails.vue
  app/javascript/mixins/manifesto-filemanager-mixins.js
  app/javascript/packs/application.js
  app/views/layouts/application.html.erb
  package.json
Labels: Review

#1932 Handles cases where the resource passed to `loadImageCollectionGql` in the Order Manager is `null`
  app/javascript/store/vuex/actions.js
Labels: Review

#1934 Ensuring that the test cases for the general IngestArchivalMediaBagJob functionality use only one Bag fixture
  spec/jobs/ingest_archival_media_bag_job_spec.rb
Labels: Review
